name: CI-CD

on: push

jobs:
  CI-CD:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip' 

      - name: Install Packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install pytest dvc dvc-http

      - name: Configure DVC for DagsHub
        env:
          DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
          DAGSHUB_USER: ${{ secrets.DAGSHUB_USER }}
        run: |
          dvc remote modify myremote url https://dagshub.com/JayeshGadhari/swiggy-delivery-time-prediction.dvc
          dvc remote modify myremote auth basic
          dvc remote modify myremote user "${DAGSHUB_USER}"
          dvc remote modify myremote password "${DAGSHUB_USER_TOKEN}"

      - name: DVC Pull from DagsHub
        run: |
          dvc pull --remote myremote || echo "❌ Some files are missing in DVC remote!"
          dvc checkout --force || echo "⚠️ Some files may not have checked out properly!"

      - name: Test Model Registry
        run: |
          pytest tests/test_model_registry.py

      - name: Test Model Performance
        run: |
          pytest tests/test_model_perf.py

      - name: Promote Model
        if: success()
        run: |
          python scripts/promote_model_to_prod.py

      - name: Run FastAPI Application
        run: |
          uvicorn app:app --host 0.0.0.0 --port 8000
